/**
 * Auto-generated test file for src/state/state-manager.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { StringRayStateManager } from "./state-manager";

describe("state-manager", () => {
  describe("StringRayStateManager", () => {
    it("should instantiate", () => {
      const instance = new StringRayStateManager();
      expect(instance).toBeInstanceOf(StringRayStateManager);
    });
  });
});
