/**
 * Auto-generated test file for src/postprocessor/monitoring/MonitoringEngine.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { PostProcessorMonitoringEngine } from "./MonitoringEngine";
import { StringRayStateManager } from "../../state/state-manager.js";

describe("MonitoringEngine", () => {
  describe("PostProcessorMonitoringEngine", () => {
    it("should instantiate", () => {
      const instance = new PostProcessorMonitoringEngine(new StringRayStateManager());
      expect(instance).toBeInstanceOf(PostProcessorMonitoringEngine);
    });
  });
});
